#!/bin/bash
#PBS -l nodes=1:ppn=6
#PBS -l vmem=16gb
#PBS -l walltime=05:00:00
command=$(jq -r .command config.json)
if [ $command == "profile" ]; then

    rm -rf results output

    time singularity exec docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/compute_profiles
    if [ ! -f output/dt6.mat ]; then
        echo "failed to product output"
        exit 1
    fi
fi
