#!/bin/bash
#PBS -l nodes=1:ppn=6
#PBS -l vmem=16gb
#PBS -l walltime=05:00:00
command=$(jq -r .command config.json)
if [ $command == "profile" ]; then

    rm -rf results output

    time singularity exec docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/compute_profiles
    if [ ! -f output/dt6.mat ]; then
        echo "failed to produce output"
        exit 1
    fi
fi

if [ $command == "remove_tracts_from_prediction" ]; then

    #rm -rf results output

    time singularity exec docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/remove_tracts_from_prediction
    if [ ! -f dwi.nii.gz ]; then
        echo "failed to produce dwi output"
        exit 1
    fi
fi

